name: Release & Publish

# Триггер: Запускается ТОЛЬКО когда вы ставите тег, начинающийся с 'v' (например, v1.0.0)
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Разрешение на создание релиза в GitHub

jobs:
  build-and-push:
    name: Build Docker Image & GitHub Release
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Настраиваем QEMU и Buildx (для быстрой и мультиплатформенной сборки)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Собираем и пушим образ в Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Собираем сразу для обычных ПК (amd64) и новых Mac/Raspberry (arm64)
          platforms: linux/amd64,linux/arm64
          tags: |
            medzhidovomar/the-oops-bay:latest
            medzhidovomar/the-oops-bay:${{ github.ref_name }}

      # 5. Создаем красивый релиз на странице GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true # Автоматически создаст список изменений из коммитов
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}